name: Python application

on:
  push:
    branches: [ $default-branch, main, master, develop]
  pull_request:
    branches: [ $default-branch, main, master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtualenv and install dependencies
        run: bash Scripts/init_env.sh

      - name: Format check
        run: bash Scripts/format_check.sh

      - name: Lint
        run: bash Scripts/lint.sh

      - name: Test with pytest
        run: bash Scripts/test.sh